namespace project_pkdsim.Generics.NPC.Species.Type
{
    public enum SpeciesType {
        Espeon,
        Flareon,
        Glaceon,
        Jolteon,
        Leafeon,
        Sylveon,
        Umbreon,
        Vaporeon,
        Noivern,
        Absol,
        Blaziken,
        Gardevoir,
        Beedrill,
        Braixen,
        Cinderace,
        Delphox,
        Dragapult,
        Frostlass,
        Garchomp,
        Hatterene,
        Lopunny,
        Lucario,
        Lunala,
        Meowscarada,
        Pheromosa,
        Primarina,
        Zoroark
    }
}